module.exports = ({simulation, subject}) ->
  simulation.on 'tick', ->
    subject.emit 'request:movement'
    subject.update()
  
  (require './move') arguments...
  (require './look') arguments...
  (require './pick') arguments...
  (require './jump') arguments...